project:
  type: book

book:
  title: "Uncertainty in Christ"
  author: "Stacy DeRuiter"
  date: "June 2023"
  chapters:
    - index.qmd
    - p-values.qmd
    - certainty-uncertainty.qmd
    - gratitude.qmd
    - kindness-ripples.qmd
    - diversity.qmd
    - something-old.qmd
    - why-model.qmd
    - brendan.qmd
    - doors.qmd
    - not-a-score.qmd
    - reciprocity.qmd
    - the-least.qmd
    - all-emotional.qmd
    - representative.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt
pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
editor: visual

