project:
  type: book

book:
  title: "Uncertainty in Christ"
  author: "Stacy DeRuiter"
  date: "Summer 2023"
  chapters:
    - index.qmd
    - p-values.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt
pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
editor: visual

