# Reciprocity

circular nature of collaboration -- partnership rather than service.
What can you offer? What are you blind to realizing that you lack? or
that others have to offer? Giving without harming

Help without hurting?

Kimmerer / Ecological?

### Matthew 20: 20-28

### A Mother\'s Request

^**20**^ Then the mother of Zebedee\'s sons came to Jesus with her sons
and, kneeling down, asked a favor of him.

^**21**^ \"What is it you want?\" he asked.

She said, \"Grant that one of these two sons of mine may sit at your
right and the other at your left in your kingdom.\"

^**22**^ \"You don\'t know what you are asking,\" Jesus said to
them. \"Can you drink the cup I am going to drink?\"

\"We can,\" they answered.

^**23**^ Jesus said to them, \"You will indeed drink from my cup, but to
sit at my right or left is not for me to grant. These places belong to
those for whom they have been prepared by my Father.\"

^**24**^ When the ten heard about this, they were indignant with the two
brothers. ^**25**^ Jesus called them together and said, \"You know that
the rulers of the Gentiles lord it over them, and their high officials
exercise authority over them. ^**26**^ Not so with you. Instead, whoever
wants to become great among you must be your servant, ^**27**^ and
whoever wants to be first must be your slave--- ^**28**^ just as the Son
of Man did not come to be served, but to serve, and to give his life as
a ransom for many.\"

*It\'s unsettling; not sure can explain it all. But the sense is that
grasping for power and recognition is not the way of the kingdom; that
it is completely on the wrong track. That our leader, our model, has the
greatest power but (unlike most of this world) combines it with the
greatest compassion; no entitlement, only service and generosity. Our
role model shows us maybe the only way to have power without letting it
corrupt.*

*This is not just theology. It is playing out in our lives every day.*

**Helping, Fixing, or Serving?**

**BY [RACHEL NAOMI
REMEN](https://www.lionsroar.com/author/rachel-naomi-remen/ "Posts by Rachel Naomi Remen")\|**

<https://www.lionsroar.com/helping-fixing-or-serving/>

Helping, fixing and serving represent three different ways of seeing
life. When you help, you see life as weak. When you fix, you see life as
broken. When you serve, you see life as whole. Fixing and helping may be
the work of the ego, and service the work of the soul.

Serving is different from helping. Helping is not a relationship between
equals. A helper may see others as weaker than they are, needier than
they are, and people often feel this inequality. The danger in helping
is that we may inadvertently take away from people more than we could
ever give them; we may diminish their self-esteem, their sense of worth,
integrity or even wholeness.

When we help, we become aware of our own strength. But when we serve, we
don\'t serve with our strength; we serve with ourselves, and we draw
from all of our experiences. 

Service is a relationship between equals: our service strengthens us as
well as others.

Serving requires us to know that our humanity is more powerful than our
expertise. In forty-five years of chronic illness I have been helped by
a great number of people, and fixed by a great many others who did not
recognize my wholeness. All that fixing and helping left me wounded in
some important and fundamental ways. Only service heals.
